services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --prefer-binary -r requirements.txt
    startCommand: gunicorn mysite.wsgi:application
    autoDeploy: true

